### PR TITLE
converge all pointer types

### PR DESCRIPTION
**Pull request by cblp**
Better solution to #97.

Launchpad to add volatile pointers.

### CODE REVIEW

**Comment by leepike** [comment]
Sorry, I didn't look at this merge request before merging #97. Can you say more about this pull request? A cursory look seems like it is more complex. You mention adding volatile pointers. Is the idea to make this generalization, allowing you to add volatile pointers on top of the framework?

**Comment by cblp** [comment]
The first reason is adding `volatile` pointers and a couple of safe cast functions. I'm working with C code with const and volatile pointers a lot, and currently just ignore GCC warnings about volatile-discarding casts. But I want to write more safe code.

The second reason is writing constancy-polymorphic or nullability-polymorphic code. For example, search in a tree of pointers must return nullable pointer (null if nothing found), but the constancy of the result must be taken from the source constancy. Also we need type families and type classes to convert pointers to const and mutable and to nullable and non-nullable. (I have some in our company's private repo.)

I think one 3-parameter type is better than 8 distinct types with many type classes around.

**Comment by leepike** [comment]
Ok, I see. That makes sense. It looks like all this will be behind the Ivory interface, so for pointers as they exist today, the API change won't matter, correct?

**Comment by leepike** [comment]
Sorry, that wasn't clear. I mean, there won't be a change to the API, correct?

**Comment by cblp** [comment]
This patch must extend API only, but I didn't updated `Ivory.Language` export list. Also, I've added a few TODOs to deprecate and remove obsolete parts.

**Comment by cblp** [comment]
updated patch

**Comment by leepike** [comment]
Ok, give me a few days. I'd like to review this @elliottt .

**Comment by cblp** [comment]
sure

**Comment by cblp** [comment]
@leepike, @elliottt, any thoughts?

**Comment by leepike** [comment]
Sorry! It's been a busy couple of weeks. I think this is the right idea. Give me until next week. Sorry for the delay. :/

**Comment by leepike** [comment]
Ok, sorry again for the delay. Looks great! I may add some light comments.

**Pull request merged**
